platform:
  - x64

cache:
  - '%AppData%/npm-cache'
  - "%LOCALAPPDATA%/Yarn"
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules\windows-build-tools

skip_branch_with_pr: true

environment:
  nodejs_version: "8"

  matrix:
  - example: gatsbygram
    buildon: commit

  - example: using-javascript-transforms
    buildon: tag

  - example: using-remark
    buildon: tag

  - example: using-contentful
    buildon: tag

  - example: using-wordpress
    buildon: tag

  - example: using-mongodb
    buildon: tag

  - example: using-typescript
    buildon: tag

  - example: no-plugins
    buildon: tag

# Install scripts. (runs after repo cloning)
install:
  - echo This example is built on %buildon% and the commit tag is %APPVEYOR_REPO_TAG% and the tag is %APPVEYOR_REPO_TAG_NAME%
    # we kill the build for most examples unless it is a release or a forced build
  - ps: |
      if (($env:buildon -eq "tag") -and ($env:APPVEYOR_REPO_COMMIT_MESSAGE -ne "Publish") -and ($env:APPVEYOR_FORCED_BUILD -ne "True"))
      {
        Exit-AppVeyorBuild
      }
  - ps: Install-Product node $env:nodejs_version $env:platform
  - ps: npm install -g windows-build-tools
  - choco install yarn --ignore-dependencies
  - refreshenv
  - echo we are running on %PLATFORM%
  - yarn global add gatsby-dev-cli@canary
  - yarn install
  - node --version
  - yarn test

# Build gatsby head
before_build:
  - yarn run build

build_script:
  - cd examples/%example%
  - yarn install
  - gatsby-dev --set-path-to-repo ../..
  - gatsby-dev --scan-once
  - yarn run build

artifacts:
  - path: examples/$(example)

deploy: off
