# branches to build
branches:
  # whitelist
  only:
    - 1.0
    - master

platform:
  - x64

environment:
  nodejs_version: "8"

  matrix:
  - example: gatsbygram
    buildon: commit

  - example: client-only-paths
    buildon: tag

  - example: hn
    buildon: tag

  - example: no-plugins
    buildon: tag

  - example: no-trailing-slashes
    buildon: tag

  - example: using-drupal
    buildon: tag

  - example: using-postcss-sass
    buildon: tag

# Install scripts. (runs after repo cloning)
install:
  - echo This example is built on %buildon% and commit is tag = %APPVEYOR_REPO_TAG%
  - ps: |
      if (($env:buildon -eq "tag") -and ($env:APPVEYOR_REPO_TAG -eq "FALSE"))
      {
        Exit-AppVeyorBuild
      }
  - ps: Install-Product node $env:nodejs_version $env:platform
  - ps: npm install -g windows-build-tools
  - npm install -g gatsby-dev-cli@canary
  #- git checkout 1.0
  - echo we are running on %PLATFORM%
  - npm install
  - node --version
  - npm --version
  - npm test

# Build gatsby head
before_build:
  - npm run build

build_script:
  - cd examples/%example%
  - npm install
  - gatsby-dev --set-path-to-repo ../..
  - gatsby-dev --scan-once
  - npm run build


deploy: off
